### ISSUE TITLE
[Feature#9]: 워크스페이스, 채널 정보 가져와서 렌더링

### ISSUE THREAD

**Issue by happydoeun** [voltnuna/flirting-education-client#9]
##Todo List

- [x] 워크스페이스 생성 및 목록 가져오기
- [x] 워크스페이스 안의 채널 생성 및 목록 가져오기 
- [x] 라우터 더미 경로 수정
